<?php
add_action('acf/include_fields', function () {
  if (! function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group(array(
    'key' => 'group_66e1936c738eb',
    'title' => 'CPT - Places',
    'fields' => array(
      array(
        'key' => 'field_66e1936c43ea9',
        'label' => 'Address',
        'name' => 'address',
        'aria-label' => '',
        'type' => 'google_map',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'center_lat' => '',
        'center_lng' => '',
        'zoom' => '',
        'height' => '',
      ),
      array(
        'key' => 'field_67230bcd1e2f3',
        'label' => 'Contact Info',
        'name' => 'contact_info',
        'aria-label' => '',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_66e1938f43eaa',
            'label' => 'Phone Number',
            'name' => 'phone_number',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_67230a6b7c8d9',
            'label' => 'Contact Email',
            'name' => 'contact_email',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => 'Email link for "Message Us" contact',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
        ),
      ),
      array(
        'key' => 'field_67230a2b3c4d5',
        'label' => 'About Content',
        'name' => 'about_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'Main descriptive content for the About tab',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'allow_in_bindings' => 1,
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array(
        'key' => 'field_67230a1b2c3d4',
        'label' => 'Gallery',
        'name' => 'gallery',
        'aria-label' => '',
        'type' => 'gallery',
        'instructions' => 'Add images for the hero carousel',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min' => '',
        'max' => '',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'insert' => 'append',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_67230a3b4c5d6',
        'label' => 'Hours Display',
        'name' => 'hours_display',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add operating hours (e.g., Mon - Fri: 9:00am - 5:00pm)',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Hours',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_67230a4b5c6d7',
            'label' => 'Hours',
            'name' => 'hours',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => 'Mon - Fri: 9:00am - 5:00pm',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_67230a3b4c5d6',
          ),
        ),
      ),
      array(
        'key' => 'field_67230a7b8c9da',
        'label' => 'Social Media Links',
        'name' => 'social_media_links',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add social media links',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Social Link',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_67230a8b9cadb',
            'label' => 'Platform Name',
            'name' => 'platform_name',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'e.g., LinkedIn, Instagram, Facebook',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => 'LinkedIn',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_67230a7b8c9da',
          ),
          array(
            'key' => 'field_67230cde2f3g4',
            'label' => 'Icon',
            'name' => 'icon',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => 'Upload an icon for this social platform',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'svg,png,jpg,jpeg',
            'preview_size' => 'thumbnail',
            'parent_repeater' => 'field_67230a7b8c9da',
          ),
          array(
            'key' => 'field_67230a9badbec',
            'label' => 'URL',
            'name' => 'url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://linkedin.com/company/...',
            'parent_repeater' => 'field_67230a7b8c9da',
          ),
        ),
      ),
      array(
        'key' => 'field_67230aabecfd1',
        'label' => 'CTA Button',
        'name' => 'cta_button',
        'aria-label' => '',
        'type' => 'link',
        'instructions' => 'Call-to-action button (e.g., "Purchase Your Season Pass Today")',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'places',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'discussion',
      3 => 'comments',
      4 => 'slug',
      5 => 'author',
      6 => 'format',
      7 => 'page_attributes',
      8 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));

  acf_add_local_field_group(array(
    'key' => 'group_66e199a44d127',
    'title' => 'Settings - Map',
    'fields' => array(
      array(
        'key' => 'field_66e199a4987ff',
        'label' => 'Google Maps API Key',
        'name' => 'google_maps_api_key',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '<a herf="https://developers.google.com/maps/documentation/javascript/overview">Visit the official Google Maps documentation</a> for more details on how to obtain an API key.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66e72f35eb454',
        'label' => 'Toggle Button Text',
        'name' => 'toggle_button_text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'The text you would like to see when the toggle button appears on mobile.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66e1a7bfcee4b',
        'label' => 'Zoom Controls',
        'name' => 'zoom_controls',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a829fec63',
        'label' => 'Map Type Controls',
        'name' => 'map_type_controls',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a836fec64',
        'label' => 'Street View Control',
        'name' => 'street_view_control',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a842fec65',
        'label' => 'Full Screen Control',
        'name' => 'full_screen_control',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1ac159eba1',
        'label' => 'Custom Marker Pin',
        'name' => 'custom_marker_pin',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_66e1aa8277613',
        'label' => 'Enable Custom Map Style?',
        'name' => 'enable_custom_map_style',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a9e935b0f',
        'label' => 'Custom Map Style',
        'name' => 'custom_map_style',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'rows' => '',
        'placeholder' => '',
        'new_lines' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'map-options',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});

add_action('acf/init', function () {
  acf_add_options_page(array(
    'page_title' => 'Map Options',
    'menu_slug' => 'map-options',
    'parent_slug' => 'edit.php?post_type=places',
    'position' => '',
    'redirect' => false,
  ));
});
