<?php
add_action('acf/include_fields', function () {
  if (! function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group(array(
    'key' => 'group_66e1936c738eb',
    'title' => 'CPT - Locations',
    'fields' => array(
      array(
        'key' => 'field_66e1936c43ea9',
        'label' => 'Address',
        'name' => 'address',
        'aria-label' => '',
        'type' => 'google_map',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'center_lat' => '',
        'center_lng' => '',
        'zoom' => '',
        'height' => '',
      ),
      array(
        'key' => 'field_66e1938f43eaa',
        'label' => 'Phone Number',
        'name' => 'phone_number',
        'aria-label' => '',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
      ),
      array(
        'key' => 'field_66e193af43eab',
        'label' => 'Details',
        'name' => 'details',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'allow_in_bindings' => 1,
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_66e1945b782b4',
        'label' => 'View More',
        'name' => 'view_more',
        'aria-label' => '',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
      ),
      array(
        'key' => 'field_66e1953527c08',
        'label' => 'Show Category Title?',
        'name' => 'show_category_title',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1955d27c09',
        'label' => 'Category Title',
        'name' => 'category_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_66e1953527c08',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'locations',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'discussion',
      3 => 'comments',
      4 => 'slug',
      5 => 'author',
      6 => 'format',
      7 => 'page_attributes',
      8 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));

  acf_add_local_field_group(array(
    'key' => 'group_66e199a44d127',
    'title' => 'Settings - Map',
    'fields' => array(
      array(
        'key' => 'field_66e199a4987ff',
        'label' => 'Google Maps API Key',
        'name' => 'google_maps_api_key',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '<a herf="https://developers.google.com/maps/documentation/javascript/overview">Visit the official Google Maps documentation</a> for more details on how to obtain an API key.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66e72f35eb454',
        'label' => 'Toggle Button Text',
        'name' => 'toggle_button_text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'The text you would like to see when the toggle button appears on mobile.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66e1a7bfcee4b',
        'label' => 'Zoom Controls',
        'name' => 'zoom_controls',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a829fec63',
        'label' => 'Map Type Controls',
        'name' => 'map_type_controls',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a836fec64',
        'label' => 'Street View Control',
        'name' => 'street_view_control',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a842fec65',
        'label' => 'Full Screen Control',
        'name' => 'full_screen_control',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1ac159eba1',
        'label' => 'Custom Marker Pin',
        'name' => 'custom_marker_pin',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_66e1aa8277613',
        'label' => 'Enable Custom Map Style?',
        'name' => 'enable_custom_map_style',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a9e935b0f',
        'label' => 'Custom Map Style',
        'name' => 'custom_map_style',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'rows' => '',
        'placeholder' => '',
        'new_lines' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'map-options',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});

add_action('acf/init', function () {
  acf_add_options_page(array(
    'page_title' => 'Map Options',
    'menu_slug' => 'map-options',
    'parent_slug' => 'edit.php?post_type=locations',
    'position' => '',
    'redirect' => false,
  ));
});
