<?php
add_action('acf/include_fields', function () {
  if (! function_exists('acf_add_local_field_group')) {
    return;
  }

  // Field Group 1: Basic Info
  acf_add_local_field_group(array(
    'key' => 'group_66e1936c738eb',
    'title' => 'CPT - Places: Basic Info',
    'fields' => array(
      array(
        'key' => 'field_66e1936c43ea9',
        'label' => 'Address',
        'name' => 'address',
        'aria-label' => '',
        'type' => 'google_map',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'center_lat' => '',
        'center_lng' => '',
        'zoom' => '',
        'height' => '',
      ),
      array(
        'key' => 'field_67230a2b3c4d5',
        'label' => 'About Content',
        'name' => 'about_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'Main descriptive content for the About tab',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'allow_in_bindings' => 1,
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array(
        'key' => 'field_67230a1b2c3d4',
        'label' => 'Gallery',
        'name' => 'gallery',
        'aria-label' => '',
        'type' => 'gallery',
        'instructions' => 'Add images for the hero carousel',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min' => '',
        'max' => '',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'insert' => 'append',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_67230a3b4c5d6',
        'label' => 'Hours Display',
        'name' => 'hours_display',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add operating hours (e.g., Mon - Fri: 9:00am - 5:00pm)',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Hours',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_67230a4b5c6d7',
            'label' => 'Hours',
            'name' => 'hours',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => 'Mon - Fri: 9:00am - 5:00pm',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_67230a3b4c5d6',
          ),
        ),
      ),
      array(
        'key' => 'field_67230bcd1e2f3',
        'label' => 'Contact Info',
        'name' => 'contact_info',
        'aria-label' => '',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_66e1938f43eaa',
            'label' => 'Phone Number',
            'name' => 'phone_number',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_67230a6b7c8d9',
            'label' => 'Contact Email',
            'name' => 'contact_email',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => 'Email link for "Message Us" contact',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
        ),
      ),
      array(
        'key' => 'field_67230a7b8c9da',
        'label' => 'Social Media Links',
        'name' => 'social_media_links',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add social media links',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Social Link',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_67230a8b9cadb',
            'label' => 'Platform Name',
            'name' => 'platform_name',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'e.g., LinkedIn, Instagram, Facebook',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => 'LinkedIn',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_67230a7b8c9da',
          ),
          array(
            'key' => 'field_67230cde2f3g4',
            'label' => 'Icon',
            'name' => 'icon',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => 'Upload an icon for this social platform',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'svg,png,jpg,jpeg',
            'preview_size' => 'thumbnail',
            'parent_repeater' => 'field_67230a7b8c9da',
          ),
          array(
            'key' => 'field_67230a9badbec',
            'label' => 'URL',
            'name' => 'url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://linkedin.com/company/...',
            'parent_repeater' => 'field_67230a7b8c9da',
          ),
        ),
      ),
      array(
        'key' => 'field_67230aabecfd1',
        'label' => 'CTA Button',
        'name' => 'cta_button',
        'aria-label' => '',
        'type' => 'link',
        'instructions' => 'Call-to-action button (e.g., "Purchase Your Season Pass Today")',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'places',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Basic place information including gallery, location, hours, and contact details',
    'show_in_rest' => 0,
  ));

  // Field Group 2: Tab Sections
  acf_add_local_field_group(array(
    'key' => 'group_672abc123def4',
    'title' => 'CPT - Places: Tab Sections',
    'fields' => array(

      // MEMBERSHIP SECTION
      array(
        'key' => 'field_672acc_membership',
        'label' => 'Membership Section',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 1,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_672tab000002',
        'label' => 'Show Membership Tab',
        'name' => 'show_membership',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable to show the Membership tab on the frontend',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => 'On',
        'ui_off_text' => 'Off',
      ),
      // Membership Tab Fields
      array(
        'key' => 'field_672mem000001',
        'label' => 'Membership',
        'name' => 'membership',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add membership options. Keep rows focused (one membership type per row).',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000002',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 1,
        'max' => 0,
        'collapsed' => 'field_672mem000002',
        'button_label' => 'Add Membership',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_672mem000002',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'Short membership title (e.g., "Annual Family Pass")',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_672mem000001',
          ),
          array(
            'key' => 'field_672mem000003',
            'label' => 'Details',
            'name' => 'details',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => 'Rich description and pricing notes',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
            'delay' => 0,
            'parent_repeater' => 'field_672mem000001',
          ),
          array(
            'key' => 'field_672mem000004',
            'label' => 'Button',
            'name' => 'button',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => 'Optional call-to-action button',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'parent_repeater' => 'field_672mem000001',
          ),
        ),
      ),
      array(
        'key' => 'field_672acc_membership_end',
        'label' => 'Accordion End',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),

      // FEATURES & RATES SECTION
      array(
        'key' => 'field_672acc_features',
        'label' => 'Features & Rates Section',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 1,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_672tab000003',
        'label' => 'Show Features & Rates Tab',
        'name' => 'show_features_rates',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable to show the Features & Rates tab on the frontend',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => 'On',
        'ui_off_text' => 'Off',
      ),
      // Features & Rates Tab Fields
      array(
        'key' => 'field_672feat000001',
        'label' => 'Features & Rates',
        'name' => 'features_rates',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add feature sections. Each section can contain multiple feature blocks.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000003',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 1,
        'max' => 0,
        'collapsed' => 'field_672feat000002',
        'button_label' => 'Add Section',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_672feat000002',
            'label' => 'Section Title',
            'name' => 'section_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50%',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_672feat000001',
          ),
          array(
            'key' => 'field_672feat000003',
            'label' => 'Show Section Title',
            'name' => 'show_section_title',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '25%',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => 'Show',
            'ui_off_text' => 'Hide',
            'parent_repeater' => 'field_672feat000001',
          ),
          array(
            'key' => 'field_672feat000004',
            'label' => 'Show Section Description',
            'name' => 'show_section_description',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '25%',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => 'Show',
            'ui_off_text' => 'Hide',
            'parent_repeater' => 'field_672feat000001',
          ),
          array(
            'key' => 'field_672feat000005',
            'label' => 'Feature Blocks',
            'name' => 'feature_blocks',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 1,
            'max' => 0,
            'collapsed' => 'field_672feat000006',
            'button_label' => 'Add Feature Block',
            'rows_per_page' => 20,
            'parent_repeater' => 'field_672feat000001',
            'sub_fields' => array(
              array(
                'key' => 'field_672feat000006',
                'label' => 'Block Title',
                'name' => 'block_title',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => 'Supports lightweight formatting (bold, lists)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
                'parent_repeater' => 'field_672feat000005',
              ),
              array(
                'key' => 'field_672feat000007',
                'label' => 'Items',
                'name' => 'items',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'table',
                'pagination' => 0,
                'min' => 1,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Item',
                'rows_per_page' => 20,
                'parent_repeater' => 'field_672feat000005',
                'sub_fields' => array(
                  array(
                    'key' => 'field_672feat000008',
                    'label' => 'Item',
                    'name' => 'item',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_672feat000007',
                  ),
                ),
              ),
            ),
          ),
          array(
            'key' => 'field_672feat000009',
            'label' => 'Section Description',
            'name' => 'section_description',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_672feat000001',
          ),
        ),
      ),
      array(
        'key' => 'field_672acc_features_end',
        'label' => 'Accordion End',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),

      // AMENITIES SECTION
      array(
        'key' => 'field_672acc_amenities',
        'label' => 'Amenities Section',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 1,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_672tab000004',
        'label' => 'Show Amenities Tab',
        'name' => 'show_amenities',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable to show the Amenities tab on the frontend',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => 'On',
        'ui_off_text' => 'Off',
      ),
      // Amenities Tab Fields
      array(
        'key' => 'field_672amen000001',
        'label' => 'Amenities',
        'name' => 'amenities_tab',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add amenity details. This is distinct from the Amenities taxonomy used for filtering.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000004',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 1,
        'max' => 0,
        'collapsed' => 'field_672amen000002',
        'button_label' => 'Add Amenity',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_672amen000002',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_672amen000001',
          ),
          array(
            'key' => 'field_672amen000003',
            'label' => 'Description',
            'name' => 'description',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => 3,
            'placeholder' => '',
            'new_lines' => 'br',
            'parent_repeater' => 'field_672amen000001',
          ),
        ),
      ),
      array(
        'key' => 'field_672acc_amenities_end',
        'label' => 'Accordion End',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),

      // PROGRAMS SECTION
      array(
        'key' => 'field_672acc_programs',
        'label' => 'Programs Section',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 1,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_672tab000005',
        'label' => 'Show Programs Tab',
        'name' => 'show_programs',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable to show the Programs tab on the frontend',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => 'On',
        'ui_off_text' => 'Off',
      ),
      // Programs Tab Fields
      array(
        'key' => 'field_672prog000001',
        'label' => 'Programs',
        'name' => 'programs',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Enter a shortcode (e.g., from a scheduling system or program list). Ensure the shortcode is safe and renders predictably.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000005',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '[program_schedule id="123"]',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_672acc_programs_end',
        'label' => 'Accordion End',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),

      // RENTALS SECTION
      array(
        'key' => 'field_672acc_rentals',
        'label' => 'Rentals Section',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 1,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_672tab000006',
        'label' => 'Show Rentals Tab',
        'name' => 'show_rentals',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable to show the Rentals tab on the frontend',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => 'On',
        'ui_off_text' => 'Off',
      ),
      // Rentals Tab Fields
      array(
        'key' => 'field_672rent000001',
        'label' => 'Rentals',
        'name' => 'rentals',
        'aria-label' => '',
        'type' => 'relationship',
        'instructions' => 'Link this Place to one or more Rentals entries. (Rentals CPT must be created first)',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000006',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'rentals',
        ),
        'post_status' => '',
        'taxonomy' => '',
        'filters' => array(
          0 => 'search',
        ),
        'return_format' => 'object',
        'min' => '',
        'max' => '',
        'elements' => '',
        'bidirectional' => 0,
        'bidirectional_target' => array(),
      ),
      array(
        'key' => 'field_672rent000002',
        'label' => 'Rentals Per Page',
        'name' => 'rentals_per_page',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => 'Maximum number of rental items to show per page. Pagination will appear if there are more rentals than this limit.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000006',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 4,
        'min' => 1,
        'max' => '',
        'step' => 1,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_672acc_rentals_end',
        'label' => 'Accordion End',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),

      // EVENTS SECTION
      array(
        'key' => 'field_672acc_events',
        'label' => 'Events Section',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 1,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_672tab000007',
        'label' => 'Show Events Tab',
        'name' => 'show_events',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable to show the Events tab on the frontend',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => 'On',
        'ui_off_text' => 'Off',
      ),
      // Events Tab Fields
      array(
        'key' => 'field_672event000005',
        'label' => 'Events Per Page',
        'name' => 'events_per_page',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => 'Maximum number of events to show per page. Pagination will appear if there are more events than this limit. Events are automatically filtered to show only those assigned to this place\'s venue.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000007',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 3,
        'min' => 1,
        'max' => '',
        'step' => 1,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_672event000006',
        'label' => 'No Events Message',
        'name' => 'no_events_message',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Custom message to display when there are no events for this place. Leave empty for default message.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000007',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'No upcoming events at this location.',
        'maxlength' => '',
        'rows' => 3,
        'placeholder' => '',
        'new_lines' => 'wpautop',
      ),
      array(
        'key' => 'field_672acc_events_end',
        'label' => 'Accordion End',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),

      // FAQS SECTION
      array(
        'key' => 'field_672acc_faqs',
        'label' => 'FAQs Section',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 1,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_672tab000008',
        'label' => 'Show FAQs Tab',
        'name' => 'show_faqs',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable to show the FAQs tab on the frontend',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => 'On',
        'ui_off_text' => 'Off',
      ),
      // FAQs Tab Fields
      array(
        'key' => 'field_672faq000001',
        'label' => 'FAQs',
        'name' => 'faqs',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Add frequently asked questions. Frontend will render as accordions with proper ARIA attributes.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_672tab000008',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 1,
        'max' => 0,
        'collapsed' => 'field_672faq000002',
        'button_label' => 'Add FAQ',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_672faq000002',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => 'The question',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_672faq000001',
          ),
          array(
            'key' => 'field_672faq000003',
            'label' => 'Content',
            'name' => 'content',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => 'The answer',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
            'delay' => 0,
            'parent_repeater' => 'field_672faq000001',
          ),
        ),
      ),
      array(
        'key' => 'field_672acc_faqs_end',
        'label' => 'Accordion End',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'places',
        ),
      ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'discussion',
      3 => 'comments',
      4 => 'slug',
      5 => 'author',
      6 => 'format',
      7 => 'page_attributes',
      8 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Configure which tabs appear on the frontend. Toggle ON to enable a tab and show its content fields.',
    'show_in_rest' => 0,
  ));

  acf_add_local_field_group(array(
    'key' => 'group_66e199a44d127',
    'title' => 'Settings - Map',
    'fields' => array(
      array(
        'key' => 'field_66e199a4987ff',
        'label' => 'Google Maps API Key',
        'name' => 'google_maps_api_key',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '<a herf="https://developers.google.com/maps/documentation/javascript/overview">Visit the official Google Maps documentation</a> for more details on how to obtain an API key.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66e72f35eb454',
        'label' => 'Toggle Button Text',
        'name' => 'toggle_button_text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'The text you would like to see when the toggle button appears on mobile.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66e1a7bfcee4b',
        'label' => 'Zoom Controls',
        'name' => 'zoom_controls',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a829fec63',
        'label' => 'Map Type Controls',
        'name' => 'map_type_controls',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a836fec64',
        'label' => 'Street View Control',
        'name' => 'street_view_control',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a842fec65',
        'label' => 'Full Screen Control',
        'name' => 'full_screen_control',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1ac159eba1',
        'label' => 'Custom Marker Pin',
        'name' => 'custom_marker_pin',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_66e1aa8277613',
        'label' => 'Enable Custom Map Style?',
        'name' => 'enable_custom_map_style',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66e1a9e935b0f',
        'label' => 'Custom Map Style',
        'name' => 'custom_map_style',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'rows' => '',
        'placeholder' => '',
        'new_lines' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'map-options',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});

add_action('acf/init', function () {
  acf_add_options_page(array(
    'page_title' => 'Map Options',
    'menu_slug' => 'map-options',
    'parent_slug' => 'edit.php?post_type=places',
    'position' => '',
    'redirect' => false,
  ));
});
