<?php
/**
 * Template Name: Single Place
 * Template Post Type: places
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>

<head>
  <meta charset="<?php bloginfo('charset'); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
  <?php wp_body_open(); ?>

  <div class="wp-site-blocks">
    <?php block_template_part('header'); ?>

    <main class="single-place">
      <?php if (have_posts()) : while (have_posts()) : the_post(); ?>

          <div class="single-place-container">

            <!-- Category Badge and Title -->
            <div class="single-place-header">
              <?php
              $location_categories = get_the_terms(get_the_ID(), 'location_category');
              if ($location_categories && !is_wp_error($location_categories)) :
                $first_category = reset($location_categories);
              ?>
                <span class="place-category-badge"><?php echo esc_html($first_category->name); ?></span>
              <?php endif; ?>

              <h1 class="place-title"><?php the_title(); ?></h1>
            </div>

            <!-- Gallery Carousel -->
            <?php
            $gallery = get_field('gallery');
            if ($gallery) :
            ?>
              <div class="place-gallery">
                <div class="gallery-carousel">
                  <?php foreach ($gallery as $image) : ?>
                    <div class="gallery-slide">
                      <img src="<?php echo esc_url($image['url']); ?>" alt="<?php echo esc_attr($image['alt']); ?>" />
                    </div>
                  <?php endforeach; ?>
                </div>
                <div class="gallery-navigation">
                  <!-- Navigation dots will be generated by JS or can be added here -->
                </div>
              </div>
            <?php endif; ?>

            <!-- Tab Navigation -->
            <?php
            // Build dynamic tab list based on toggles and data presence
            $available_tabs = array();

            // About tab (always check for content, no toggle)
            $about_content = get_field('about_content');
            if (!empty($about_content)) {
              $available_tabs[] = array(
                'id' => 'about',
                'label' => 'ABOUT'
              );
            }

            // Membership
            $show_membership = get_field('show_membership');
            if (!empty($show_membership)) {
              $membership = get_field('membership');
              if (!empty($membership) && is_array($membership)) {
                $available_tabs[] = array(
                  'id' => 'membership',
                  'label' => 'MEMBERSHIP'
                );
              }
            }

            // Features & Rates
            $show_features_rates = get_field('show_features_rates');
            if (!empty($show_features_rates)) {
              $features_rates = get_field('features_rates');
              if (!empty($features_rates) && is_array($features_rates)) {
                $available_tabs[] = array(
                  'id' => 'features',
                  'label' => 'FEATURES & RATES'
                );
              }
            }

            // Amenities
            $show_amenities = get_field('show_amenities');
            if (!empty($show_amenities)) {
              $amenities_tab = get_field('amenities_tab');
              if (!empty($amenities_tab) && is_array($amenities_tab)) {
                $available_tabs[] = array(
                  'id' => 'amenities',
                  'label' => 'AMENITIES'
                );
              }
            }

            // Programs
            $show_programs = get_field('show_programs');
            if (!empty($show_programs)) {
              $programs = get_field('programs');
              if (!empty($programs)) {
                $available_tabs[] = array(
                  'id' => 'programs',
                  'label' => 'PROGRAMS'
                );
              }
            }

            // Rentals
            $show_rentals = get_field('show_rentals');
            if (!empty($show_rentals)) {
              $rentals = get_field('rentals');
              if (!empty($rentals) && is_array($rentals)) {
                $available_tabs[] = array(
                  'id' => 'rentals',
                  'label' => 'RENTALS'
                );
              }
            }

            // Events
            $show_events = get_field('show_events');
            if (!empty($show_events)) {
              $events_tab = get_field('events_tab');
              // Events tab is available if configured
              if (!empty($events_tab['event_selection_mode'])) {
                $available_tabs[] = array(
                  'id' => 'events',
                  'label' => 'EVENTS'
                );
              }
            }

            // FAQs
            $show_faqs = get_field('show_faqs');
            if (!empty($show_faqs)) {
              $faqs = get_field('faqs');
              if (!empty($faqs) && is_array($faqs)) {
                $available_tabs[] = array(
                  'id' => 'faqs',
                  'label' => 'FAQS'
                );
              }
            }

            // Render tabs if any are available
            if (!empty($available_tabs)) :
            ?>
              <nav class="place-tabs" role="tablist" aria-label="Place information tabs">
                <?php foreach ($available_tabs as $index => $tab) : ?>
                  <button
                    class="tab-button<?php echo $index === 0 ? ' active' : ''; ?>"
                    data-tab="<?php echo esc_attr($tab['id']); ?>"
                    role="tab"
                    aria-selected="<?php echo $index === 0 ? 'true' : 'false'; ?>"
                    aria-controls="tab-<?php echo esc_attr($tab['id']); ?>"
                    id="btn-<?php echo esc_attr($tab['id']); ?>"
                    tabindex="<?php echo $index === 0 ? '0' : '-1'; ?>"
                  >
                    <?php echo esc_html($tab['label']); ?>
                  </button>
                <?php endforeach; ?>
              </nav>
            <?php endif; ?>

            <!-- Two Column Layout -->
            <div class="place-content-wrapper">

              <!-- Left Column: Main Content -->
              <div class="place-main-content">

                <?php if (!empty($about_content)) : ?>
                <div class="tab-content active" id="tab-about" role="tabpanel" aria-labelledby="btn-about" tabindex="0">
                  <h2>About</h2>
                  <?php echo $about_content; ?>
                </div>
                <?php endif; ?>

                <?php
                // Membership Tab
                if (!empty($show_membership) && !empty($membership) && is_array($membership)) :
                ?>
                <div class="tab-content" id="tab-membership" role="tabpanel" aria-labelledby="btn-membership" tabindex="0" hidden>
                  <h2>Membership</h2>
                  <div class="membership-list">
                    <?php foreach ($membership as $member) : ?>
                      <div class="membership-item">
                        <?php if (!empty($member['title'])) : ?>
                          <h3><?php echo esc_html($member['title']); ?></h3>
                        <?php endif; ?>
                        <?php if (!empty($member['details'])) : ?>
                          <div class="membership-details">
                            <?php echo $member['details']; ?>
                          </div>
                        <?php endif; ?>
                        <?php if (!empty($member['button']) && !empty($member['button']['url'])) : ?>
                          <a href="<?php echo esc_url($member['button']['url']); ?>" class="membership-button" target="<?php echo esc_attr($member['button']['target'] ? $member['button']['target'] : '_self'); ?>">
                            <?php echo esc_html($member['button']['title']); ?>
                          </a>
                        <?php endif; ?>
                      </div>
                    <?php endforeach; ?>
                  </div>
                </div>
                <?php endif; ?>

                <?php
                // Features & Rates Tab
                if (!empty($show_features_rates) && !empty($features_rates) && is_array($features_rates)) :
                ?>
                <div class="tab-content" id="tab-features" role="tabpanel" aria-labelledby="btn-features" tabindex="0" hidden>
                  <h2>Features & Rates</h2>
                  <div class="features-rates-list">
                    <?php foreach ($features_rates as $section) : ?>
                      <div class="features-section">
                        <?php if (!empty($section['show_section_title']) && !empty($section['section_title'])) : ?>
                          <h3><?php echo esc_html($section['section_title']); ?></h3>
                        <?php endif; ?>

                        <?php if (!empty($section['feature_blocks']) && is_array($section['feature_blocks'])) : ?>
                          <div class="feature-blocks">
                            <?php foreach ($section['feature_blocks'] as $block) : ?>
                              <div class="feature-block">
                                <?php if (!empty($block['block_title'])) : ?>
                                  <div class="feature-block-title">
                                    <?php echo $block['block_title']; ?>
                                  </div>
                                <?php endif; ?>
                                <?php if (!empty($block['items']) && is_array($block['items'])) : ?>
                                  <ul class="feature-items">
                                    <?php foreach ($block['items'] as $item) : ?>
                                      <?php if (!empty($item['item'])) : ?>
                                        <li><?php echo esc_html($item['item']); ?></li>
                                      <?php endif; ?>
                                    <?php endforeach; ?>
                                  </ul>
                                <?php endif; ?>
                              </div>
                            <?php endforeach; ?>
                          </div>
                        <?php endif; ?>

                        <?php if (!empty($section['show_section_description']) && !empty($section['section_description'])) : ?>
                          <p class="section-description"><?php echo esc_html($section['section_description']); ?></p>
                        <?php endif; ?>
                      </div>
                    <?php endforeach; ?>
                  </div>
                </div>
                <?php endif; ?>

                <?php
                // Amenities Tab
                if (!empty($show_amenities) && !empty($amenities_tab) && is_array($amenities_tab)) :
                ?>
                <div class="tab-content" id="tab-amenities" role="tabpanel" aria-labelledby="btn-amenities" tabindex="0" hidden>
                  <h2>Amenities</h2>
                  <div class="amenities-list">
                    <?php foreach ($amenities_tab as $amenity) : ?>
                      <div class="amenity-item">
                        <?php if (!empty($amenity['title'])) : ?>
                          <h3><?php echo esc_html($amenity['title']); ?></h3>
                        <?php endif; ?>
                        <?php if (!empty($amenity['description'])) : ?>
                          <p><?php echo nl2br(esc_html($amenity['description'])); ?></p>
                        <?php endif; ?>
                      </div>
                    <?php endforeach; ?>
                  </div>
                </div>
                <?php endif; ?>

                <?php
                // Programs Tab
                if (!empty($show_programs) && !empty($programs)) :
                ?>
                <div class="tab-content" id="tab-programs" role="tabpanel" aria-labelledby="btn-programs" tabindex="0" hidden>
                  <h2>Programs</h2>
                  <div class="programs-content">
                    <?php echo do_shortcode($programs); ?>
                  </div>
                </div>
                <?php endif; ?>

                <?php
                // Rentals Tab
                if (!empty($show_rentals) && !empty($rentals) && is_array($rentals)) :
                ?>
                <div class="tab-content" id="tab-rentals" role="tabpanel" aria-labelledby="btn-rentals" tabindex="0" hidden>
                  <h2>Rentals</h2>
                  <div class="rentals-list">
                    <?php foreach ($rentals as $rental) : ?>
                      <div class="rental-item">
                        <h3>
                          <a href="<?php echo esc_url(get_permalink($rental->ID)); ?>">
                            <?php echo esc_html($rental->post_title); ?>
                          </a>
                        </h3>
                        <?php if (!empty($rental->post_excerpt)) : ?>
                          <p><?php echo esc_html($rental->post_excerpt); ?></p>
                        <?php endif; ?>
                      </div>
                    <?php endforeach; ?>
                  </div>
                </div>
                <?php endif; ?>

                <?php
                // Events Tab
                if (!empty($show_events) && !empty($events_tab['event_selection_mode'])) :
                  $event_mode = $events_tab['event_selection_mode'];
                  $max_events = !empty($events_tab['max_events']) ? intval($events_tab['max_events']) : 3;
                  $events_query_args = array(
                    'post_type' => 'tribe_events',
                    'posts_per_page' => $max_events,
                    'post_status' => 'publish',
                    'orderby' => 'event_date',
                    'order' => 'ASC',
                    'meta_key' => '_EventStartDate',
                    'meta_query' => array(
                      array(
                        'key' => '_EventStartDate',
                        'value' => current_time('Y-m-d H:i:s'),
                        'compare' => '>=',
                        'type' => 'DATETIME'
                      )
                    )
                  );

                  // Add venue/location filtering based on mode
                  if ($event_mode === 'venue' && !empty($events_tab['tec_venue'])) {
                    $events_query_args['meta_query'][] = array(
                      'key' => '_EventVenueID',
                      'value' => $events_tab['tec_venue'],
                      'compare' => '='
                    );
                  } elseif ($event_mode === 'location' && !empty($events_tab['linked_location'])) {
                    // Custom location logic would go here
                  }

                  $events_query = new WP_Query($events_query_args);
                ?>
                <div class="tab-content" id="tab-events" role="tabpanel" aria-labelledby="btn-events" tabindex="0" hidden>
                  <h2>Events</h2>
                  <div class="events-list" data-max-events="<?php echo esc_attr($max_events); ?>" data-event-mode="<?php echo esc_attr($event_mode); ?>">
                    <?php if ($events_query->have_posts()) : ?>
                      <?php while ($events_query->have_posts()) : $events_query->the_post(); ?>
                        <div class="event-item">
                          <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
                          <?php if (function_exists('tribe_get_start_date')) : ?>
                            <p class="event-date"><?php echo tribe_get_start_date(get_the_ID(), false, 'F j, Y g:i a'); ?></p>
                          <?php endif; ?>
                          <?php if (has_excerpt()) : ?>
                            <p><?php the_excerpt(); ?></p>
                          <?php endif; ?>
                        </div>
                      <?php endwhile; ?>
                      <?php wp_reset_postdata(); ?>
                    <?php else : ?>
                      <p>No upcoming events found.</p>
                    <?php endif; ?>
                  </div>
                </div>
                <?php endif; ?>

                <?php
                // FAQs Tab
                if (!empty($show_faqs) && !empty($faqs) && is_array($faqs)) :
                ?>
                <div class="tab-content" id="tab-faqs" role="tabpanel" aria-labelledby="btn-faqs" tabindex="0" hidden>
                  <h2>FAQs</h2>
                  <div class="faqs-list">
                    <?php foreach ($faqs as $index => $faq) : ?>
                      <div class="faq-item">
                        <button class="faq-question" aria-expanded="false" aria-controls="faq-answer-<?php echo esc_attr($index); ?>" id="faq-btn-<?php echo esc_attr($index); ?>">
                          <?php echo esc_html($faq['title']); ?>
                        </button>
                        <div class="faq-answer" id="faq-answer-<?php echo esc_attr($index); ?>" aria-labelledby="faq-btn-<?php echo esc_attr($index); ?>" hidden>
                          <?php echo $faq['content']; ?>
                        </div>
                      </div>
                    <?php endforeach; ?>
                  </div>
                </div>
                <?php endif; ?>

              </div>

              <!-- Right Column: Sidebar -->
              <aside class="place-sidebar">

                <!-- Hours Display -->
                <?php
                $hours_display = get_field('hours_display');
                if ($hours_display) :
                ?>
                  <div class="sidebar-section hours-section">
                    <h3>Hours</h3>
                    <div class="hours-list">
                      <svg class="icon icon-clock" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="10" cy="10" r="9" stroke="currentColor" stroke-width="2" />
                        <path d="M10 5V10L13 13" stroke="currentColor" stroke-width="2" stroke-linecap="round" />
                      </svg>
                      <?php foreach ($hours_display as $hours_item) : ?>
                        <?php if (isset($hours_item['hours'])) : ?>
                          <div class="hours-item"><?php echo esc_html($hours_item['hours']); ?></div>
                        <?php endif; ?>
                      <?php endforeach; ?>
                    </div>
                  </div>
                <?php endif; ?>

                <!-- Contact Info -->
                <?php
                $contact_info = get_field('contact_info');
                if ($contact_info) :
                ?>
                  <div class="sidebar-section contact-section">
                    <h3>Contact Info</h3>
                    <div class="contact-list">
                      <?php
                      $phone = $contact_info['phone_number'];
                      if ($phone) :
                      ?>
                        <a href="<?php echo esc_url($phone['url']); ?>" class="contact-item phone-item">
                          <svg class="icon icon-phone" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M18 13.5V16.5C18 17.0523 17.5523 17.5 17 17.5H15C8.37258 17.5 3 12.1274 3 5.5V3.5C3 2.94772 3.44772 2.5 4 2.5H7L8.5 6.5L6.5 8C7.5 10 10 12.5 12 13.5L13.5 11.5L17.5 13L18 13.5Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                          </svg>
                          <span><?php echo esc_html($phone['title']); ?></span>
                        </a>
                      <?php endif; ?>

                      <?php
                      $email = $contact_info['contact_email'];
                      if ($email) :
                      ?>
                        <a href="<?php echo esc_url($email['url']); ?>" class="contact-item email-item">
                          <svg class="icon icon-email" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <rect x="2" y="4" width="16" height="12" rx="2" stroke="currentColor" stroke-width="2" />
                            <path d="M2 6L10 11L18 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                          </svg>
                          <span><?php echo esc_html($email['title'] ? $email['title'] : 'Message Us'); ?></span>
                        </a>
                      <?php endif; ?>
                    </div>
                  </div>
                <?php endif; ?>

                <!-- Social Media -->
                <?php
                $social_links = get_field('social_media_links');
                if ($social_links) :
                ?>
                  <div class="sidebar-section socials-section">
                    <h3>Socials</h3>
                    <div class="social-links">
                      <?php foreach ($social_links as $social) : ?>
                        <a href="<?php echo esc_url($social['url']); ?>" class="social-link" target="_blank" rel="noopener">
                          <?php if ($social['icon']) : ?>
                            <img src="<?php echo esc_url($social['icon']['url']); ?>" alt="<?php echo esc_attr($social['platform_name']); ?>" />
                          <?php else : ?>
                            <span><?php echo esc_html($social['platform_name']); ?></span>
                          <?php endif; ?>
                        </a>
                      <?php endforeach; ?>
                    </div>
                  </div>
                <?php endif; ?>

                <!-- Location Map -->
                <?php
                $address = get_field('address');
                if ($address) :
                ?>
                  <div class="sidebar-section map-section">
                    <h3>Location Map</h3>
                    <div class="map-address">
                      <svg class="icon icon-pin" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10 2C6.68629 2 4 4.68629 4 8C4 11.3137 10 18 10 18C10 18 16 11.3137 16 8C16 4.68629 13.3137 2 10 2Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                        <circle cx="10" cy="8" r="2" stroke="currentColor" stroke-width="2" />
                      </svg>
                      <span><?php echo esc_html($address['address']); ?></span>
                    </div>
                    <div class="map-embed">
                      <div class="acf-map" style="width: 100%; height: 300px;">
                        <div class="marker" data-lat="<?php echo esc_attr($address['lat']); ?>" data-lng="<?php echo esc_attr($address['lng']); ?>"></div>
                      </div>
                    </div>
                  </div>

                  <script>
                    (function() {
                      function initMap(el) {
                        const markers = el.querySelectorAll('.marker');
                        const args = {
                          zoom: 16,
                          center: new google.maps.LatLng(0, 0),
                          mapTypeId: google.maps.MapTypeId.ROADMAP
                        };
                        const map = new google.maps.Map(el, args);
                        map.markers = [];

                        markers.forEach(function(markerEl) {
                          initMarker(markerEl, map);
                        });

                        centerMap(map);
                      }

                      function initMarker(markerEl, map) {
                        const lat = markerEl.getAttribute('data-lat');
                        const lng = markerEl.getAttribute('data-lng');
                        const latLng = {
                          lat: parseFloat(lat),
                          lng: parseFloat(lng)
                        };

                        const marker = new google.maps.Marker({
                          position: latLng,
                          map: map
                        });

                        map.markers.push(marker);
                      }

                      function centerMap(map) {
                        const bounds = new google.maps.LatLngBounds();
                        map.markers.forEach(function(marker) {
                          bounds.extend({
                            lat: marker.position.lat(),
                            lng: marker.position.lng()
                          });
                        });

                        if (map.markers.length === 1) {
                          map.setCenter(bounds.getCenter());
                          map.setZoom(16);
                        } else {
                          map.fitBounds(bounds);
                        }
                      }

                      function initAllMaps() {
                        const mapElements = document.querySelectorAll('.acf-map');
                        mapElements.forEach(function(mapEl) {
                          initMap(mapEl);
                        });
                      }

                      function waitForGoogleMaps() {
                        if (typeof google !== 'undefined' && typeof google.maps !== 'undefined') {
                          initAllMaps();
                        } else {
                          // Retry every 100ms until Google Maps is loaded
                          setTimeout(waitForGoogleMaps, 100);
                        }
                      }

                      // Start waiting for Google Maps to load
                      if (document.readyState === 'loading') {
                        document.addEventListener('DOMContentLoaded', waitForGoogleMaps);
                      } else {
                        waitForGoogleMaps();
                      }
                    })();
                  </script>
                <?php endif; ?>

                <!-- CTA Button -->
                <?php
                $cta_button = get_field('cta_button');
                if ($cta_button) :
                ?>
                  <div class="sidebar-section cta-section">
                    <a href="<?php echo esc_url($cta_button['url']); ?>" class="cta-button" target="<?php echo esc_attr($cta_button['target'] ? $cta_button['target'] : '_self'); ?>">
                      <?php echo esc_html($cta_button['title']); ?>
                    </a>
                  </div>
                <?php endif; ?>

              </aside>

            </div>

          </div>

      <?php endwhile;
      endif; ?>
    </main>

    <?php block_template_part('footer'); ?>
  </div>

  <?php wp_footer(); ?>
</body>

</html>