<?php
/**
 * Template Name: Single Place
 * Template Post Type: places
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>

<head>
  <meta charset="<?php bloginfo('charset'); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
  <?php wp_body_open(); ?>

  <div class="wp-site-blocks">
    <?php block_template_part('header'); ?>

    <main class="single-place">
      <?php if (have_posts()) : while (have_posts()) : the_post(); ?>

          <div class="single-place-container">

            <!-- Category Badge and Title -->
            <div class="single-place-header">
              <?php
              $location_categories = get_the_terms(get_the_ID(), 'location_category');
              if ($location_categories && !is_wp_error($location_categories)) :
                $first_category = reset($location_categories);
              ?>
                <span class="place-category-badge"><?php echo esc_html($first_category->name); ?></span>
              <?php endif; ?>

              <h1 class="place-title"><?php the_title(); ?></h1>
            </div>

            <!-- Gallery Carousel -->
            <?php
            $gallery = get_field('gallery');
            if ($gallery) :
            ?>
              <div class="place-gallery">
                <div class="gallery-carousel">
                  <?php foreach ($gallery as $image) : ?>
                    <div class="gallery-slide">
                      <img src="<?php echo esc_url($image['url']); ?>" alt="<?php echo esc_attr($image['alt']); ?>" />
                    </div>
                  <?php endforeach; ?>
                </div>
                <div class="gallery-navigation">
                  <!-- Navigation dots will be generated by JS or can be added here -->
                </div>
              </div>
            <?php endif; ?>

            <!-- Tab Navigation -->
            <nav class="place-tabs">
              <button class="tab-button active" data-tab="about">ABOUT</button>
              <button class="tab-button" data-tab="memberships">MEMBERSHIPS</button>
              <button class="tab-button" data-tab="features">FEATURES & RATES</button>
              <button class="tab-button" data-tab="amenities">AMENITIES</button>
              <button class="tab-button" data-tab="programs">PROGRAMS</button>
              <button class="tab-button" data-tab="rentals">RENTALS</button>
              <button class="tab-button" data-tab="events">EVENTS</button>
            </nav>

            <!-- Two Column Layout -->
            <div class="place-content-wrapper">

              <!-- Left Column: Main Content -->
              <div class="place-main-content">
                <div class="tab-content active" id="tab-about">
                  <h2>About</h2>
                  <?php
                  $about_content = get_field('about_content');
                  if ($about_content) {
                    echo $about_content;
                  }
                  ?>
                </div>

                <!-- Placeholder tabs for future content -->
                <div class="tab-content" id="tab-memberships">
                  <h2>Memberships</h2>
                  <p>Memberships content coming soon.</p>
                </div>

                <div class="tab-content" id="tab-features">
                  <h2>Features & Rates</h2>
                  <p>Features & Rates content coming soon.</p>
                </div>

                <div class="tab-content" id="tab-amenities">
                  <h2>Amenities</h2>
                  <p>Amenities content coming soon.</p>
                </div>

                <div class="tab-content" id="tab-programs">
                  <h2>Programs</h2>
                  <p>Programs content coming soon.</p>
                </div>

                <div class="tab-content" id="tab-rentals">
                  <h2>Rentals</h2>
                  <p>Rentals content coming soon.</p>
                </div>

                <div class="tab-content" id="tab-events">
                  <h2>Events</h2>
                  <p>Events content coming soon.</p>
                </div>
              </div>

              <!-- Right Column: Sidebar -->
              <aside class="place-sidebar">

                <!-- Hours Display -->
                <?php
                $hours_display = get_field('hours_display');
                if ($hours_display) :
                ?>
                  <div class="sidebar-section hours-section">
                    <h3>Hours</h3>
                    <div class="hours-list">
                      <svg class="icon icon-clock" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="10" cy="10" r="9" stroke="currentColor" stroke-width="2" />
                        <path d="M10 5V10L13 13" stroke="currentColor" stroke-width="2" stroke-linecap="round" />
                      </svg>
                      <?php foreach ($hours_display as $hours_item) : ?>
                        <?php if (isset($hours_item['hours'])) : ?>
                          <div class="hours-item"><?php echo esc_html($hours_item['hours']); ?></div>
                        <?php endif; ?>
                      <?php endforeach; ?>
                    </div>
                  </div>
                <?php endif; ?>

                <!-- Contact Info -->
                <?php
                $contact_info = get_field('contact_info');
                if ($contact_info) :
                ?>
                  <div class="sidebar-section contact-section">
                    <h3>Contact Info</h3>
                    <div class="contact-list">
                      <?php
                      $phone = $contact_info['phone_number'];
                      if ($phone) :
                      ?>
                        <a href="<?php echo esc_url($phone['url']); ?>" class="contact-item phone-item">
                          <svg class="icon icon-phone" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M18 13.5V16.5C18 17.0523 17.5523 17.5 17 17.5H15C8.37258 17.5 3 12.1274 3 5.5V3.5C3 2.94772 3.44772 2.5 4 2.5H7L8.5 6.5L6.5 8C7.5 10 10 12.5 12 13.5L13.5 11.5L17.5 13L18 13.5Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                          </svg>
                          <span><?php echo esc_html($phone['title']); ?></span>
                        </a>
                      <?php endif; ?>

                      <?php
                      $email = $contact_info['contact_email'];
                      if ($email) :
                      ?>
                        <a href="<?php echo esc_url($email['url']); ?>" class="contact-item email-item">
                          <svg class="icon icon-email" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <rect x="2" y="4" width="16" height="12" rx="2" stroke="currentColor" stroke-width="2" />
                            <path d="M2 6L10 11L18 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                          </svg>
                          <span><?php echo esc_html($email['title'] ? $email['title'] : 'Message Us'); ?></span>
                        </a>
                      <?php endif; ?>
                    </div>
                  </div>
                <?php endif; ?>

                <!-- Social Media -->
                <?php
                $social_links = get_field('social_media_links');
                if ($social_links) :
                ?>
                  <div class="sidebar-section socials-section">
                    <h3>Socials</h3>
                    <div class="social-links">
                      <?php foreach ($social_links as $social) : ?>
                        <a href="<?php echo esc_url($social['url']); ?>" class="social-link" target="_blank" rel="noopener">
                          <?php if ($social['icon']) : ?>
                            <img src="<?php echo esc_url($social['icon']['url']); ?>" alt="<?php echo esc_attr($social['platform_name']); ?>" />
                          <?php else : ?>
                            <span><?php echo esc_html($social['platform_name']); ?></span>
                          <?php endif; ?>
                        </a>
                      <?php endforeach; ?>
                    </div>
                  </div>
                <?php endif; ?>

                <!-- Location Map -->
                <?php
                $address = get_field('address');
                if ($address) :
                ?>
                  <div class="sidebar-section map-section">
                    <h3>Location Map</h3>
                    <div class="map-address">
                      <svg class="icon icon-pin" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10 2C6.68629 2 4 4.68629 4 8C4 11.3137 10 18 10 18C10 18 16 11.3137 16 8C16 4.68629 13.3137 2 10 2Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                        <circle cx="10" cy="8" r="2" stroke="currentColor" stroke-width="2" />
                      </svg>
                      <span><?php echo esc_html($address['address']); ?></span>
                    </div>
                    <div class="map-embed">
                      <div class="acf-map" style="width: 100%; height: 300px;">
                        <div class="marker" data-lat="<?php echo esc_attr($address['lat']); ?>" data-lng="<?php echo esc_attr($address['lng']); ?>"></div>
                      </div>
                    </div>
                  </div>

                  <script>
                    (function() {
                      function initMap(el) {
                        const markers = el.querySelectorAll('.marker');
                        const args = {
                          zoom: 16,
                          center: new google.maps.LatLng(0, 0),
                          mapTypeId: google.maps.MapTypeId.ROADMAP
                        };
                        const map = new google.maps.Map(el, args);
                        map.markers = [];

                        markers.forEach(function(markerEl) {
                          initMarker(markerEl, map);
                        });

                        centerMap(map);
                      }

                      function initMarker(markerEl, map) {
                        const lat = markerEl.getAttribute('data-lat');
                        const lng = markerEl.getAttribute('data-lng');
                        const latLng = {
                          lat: parseFloat(lat),
                          lng: parseFloat(lng)
                        };

                        const marker = new google.maps.Marker({
                          position: latLng,
                          map: map
                        });

                        map.markers.push(marker);
                      }

                      function centerMap(map) {
                        const bounds = new google.maps.LatLngBounds();
                        map.markers.forEach(function(marker) {
                          bounds.extend({
                            lat: marker.position.lat(),
                            lng: marker.position.lng()
                          });
                        });

                        if (map.markers.length === 1) {
                          map.setCenter(bounds.getCenter());
                          map.setZoom(16);
                        } else {
                          map.fitBounds(bounds);
                        }
                      }

                      function initAllMaps() {
                        const mapElements = document.querySelectorAll('.acf-map');
                        mapElements.forEach(function(mapEl) {
                          initMap(mapEl);
                        });
                      }

                      function waitForGoogleMaps() {
                        if (typeof google !== 'undefined' && typeof google.maps !== 'undefined') {
                          initAllMaps();
                        } else {
                          // Retry every 100ms until Google Maps is loaded
                          setTimeout(waitForGoogleMaps, 100);
                        }
                      }

                      // Start waiting for Google Maps to load
                      if (document.readyState === 'loading') {
                        document.addEventListener('DOMContentLoaded', waitForGoogleMaps);
                      } else {
                        waitForGoogleMaps();
                      }
                    })();
                  </script>
                <?php endif; ?>

                <!-- CTA Button -->
                <?php
                $cta_button = get_field('cta_button');
                if ($cta_button) :
                ?>
                  <div class="sidebar-section cta-section">
                    <a href="<?php echo esc_url($cta_button['url']); ?>" class="cta-button" target="<?php echo esc_attr($cta_button['target'] ? $cta_button['target'] : '_self'); ?>">
                      <?php echo esc_html($cta_button['title']); ?>
                    </a>
                  </div>
                <?php endif; ?>

              </aside>

            </div>

          </div>

      <?php endwhile;
      endif; ?>
    </main>

    <?php block_template_part('footer'); ?>
  </div>

  <?php wp_footer(); ?>
</body>

</html>